config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get    "home",   to: "home#index"
  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "logout", to: "sessions#destroy"
  get    "signup", to: "users#new"  #to routes into users/new.html.erb
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy]do
  member do
    get :following
    get :followers
  end
end
  resources :tweets, only: [:index, :create ,:destroy]


  resource  :relationship, only: [:create, :destroy]   #
  resolve("Relationship") { :relationship } #resolve polymorphic mappings from join table Relationship model to URL

  get "help",  to: "static_pages#help"   ###to render in the footer in the layout 
  get "about", to: "static_pages#about"  ###to render in the footer in the layout 
  # Defines the root path route ("/")
  # root "articles#index"

  resources :tweets do
    member do
      put 'like', to: 'tweets#like'    #put 'like', to: 'posts#upvote'
      put 'liked', to: 'tweets#liked'
    end
  end
  ######################## routes for comment ##############
  resources :comments, only: [:new, :create, :destroy]
  


end

app/models/tweet.rb
class Tweet < ApplicationRecord
    acts_as_votable

    
    belongs_to :user

    ################ comments ###################
    has_many :comments, dependent: :destroy
    has_one_attached :image  #to render image in the tweets controller

    validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a valid image format" }

    def display_image
        image.variant(resize_to_limit: [700, 700])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  #before_action :require_login, except: :new #### to restrict non-logged-in users
  before_action :correct_user, only: [:destroy]
    def index
        @tweets = Tweet.includes(:user).with_attached_image.paginate(page: params[:page])
        render "home/index"
    end
    def create
        @tweet = current_user.tweets.build(tweet_params)
        @tweet.image.attach(tweet_params[:image])
        if @tweet.save
          flash[:success] = "Tweet created!"
          redirect_to root_url
        else
          flash[:danger] = @tweet.errors.full_messages.to_sentence
          redirect_to root_url
        end
    end
    ############################# delete tweet #####################
    def destroy
      @tweet.destroy
      redirect_to root_url
    end

    ########################## like and dislike #################################
    def like
      @tweet=Tweet.find(params[:id]) #@tweet = current_user.tweets.find(params[:id])
      @tweet.liked_by current_user
      redirect_back fallback_location: root_path
    end

    def liked
      @tweet=Tweet.find(params[:id]) #@tweet = current_user.tweets.find(params[:id])
      @tweet.unliked_by current_user
      redirect_back fallback_location: root_path
    end
    
    # def like 
    #   @tweet=Tweet.find(params[:id])
    #   if params[:format]=='like'
    #     @tweet.liked_by current_user
    #   elsif params[:format]=='unlike'
    #     @tweet.unliked_by current_user
    #   end
    # end

    private
    def tweet_params
        params.require(:tweet).permit(:content, :image)
    end
    def correct_user
      @tweet = current_user.tweets.find_by(id: params[:id])
      redirect_to root_url if @tweet.nil?
    end

    #### to restrict non-logged-in users
    # def require_login
    #   unless logged_in?
    #     flash[:error] = "You must be logged in to access this section"
    #     redirect_to(root_path) # halts request cycle
    #   end
    # end
    
    
    
    
    
end

app/views/tweets/_tweet.html.erb
<li class="tweet clearfix">
  <%= link_to gravatar_for(tweet.user), tweet.user %>
  <div class="content">
    <div class="user">
      <%= link_to tweet.user.name, tweet.user %>
    </div>
    <div class="tweet-content">
      <%= tweet.content %>
      <% if tweet.image.attached? %>
        <div class="tweet-img">
          <%= image_tag tweet.display_image, class: 'img-fluid rounded' %>
        </div>
      <% end %>
      <a>
      <%if current_user.liked? tweet%>
        <div><%= button_to liked_tweet_path(tweet), method: :put, remote: :true do%> liked </div>
        <%end%>
      <%elsif%>
        <div><%= button_to like_tweet_path(tweet), method: :put do%> like </div>
        <%end%>
      <%end%>
      <a>
    </div>
    <div> 
      <%byebug%> 
        <%= form_for :comment, url: comments_path do |f| %>
        <%= gravatar_for current_user, size: 32 %>
        <%= f.text_area :content, placeholder: "Write a comment...", required: true %>
        <div class="action">
          <%= f.submit "Submit" %>
        </div>
<% end %>

    </div>
    <div class="tweet-footer">
      <time>
        <%= time_ago_in_words(tweet.created_at) %> ago.
      </time>
      <% if current_user?(tweet.user) %>
        <div class="tweet-actions">
          <%= button_to "delete", tweet, method: :delete, data: { confirm: "Delete Tweet?" } %>
        </div>
      <% end %>
    </div>
  </div>
</li>






    