config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get    "home",   to: "home#index"
  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "logout", to: "sessions#destroy"
  get    "signup", to: "users#new"  #to routes into users/new.html.erb
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy]do
  member do
    get :following
    get :followers
  end
end
  resources :tweets, only: [:index, :create ,:destroy]


  resource  :relationship, only: [:create, :destroy]   #
  resolve("Relationship") { :relationship } #resolve polymorphic mappings from join table Relationship model to URL

  get "help",  to: "static_pages#help"   ###to render in the footer in the layout 
  get "about", to: "static_pages#about"  ###to render in the footer in the layout 
  # Defines the root path route ("/")
  # root "articles#index"

  resources :tweets do
    member do
      put 'like', to: 'tweets#like'    #put 'like', to: 'posts#upvote'
      put 'liked', to: 'tweets#liked'
    end
  end
  ######################## routes for comment ##############
  resources :comments, only: [:new, :create, :destroy]
  


end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <%= link_to "Help", help_path %>
  <%= link_to "About", about_path  %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light border-bottom">
  <div class="container-fluid">
    <%= link_to "Twitter Clone", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <% if logged_in? %>
          <%# TODO: handle active class %>
          <li class="nav-item">
            <%= link_to users_path, class: 'nav-link', aria: { current: 'page' } do %>
              <%= inline_svg_tag("bootstrap-icons/people.svg") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to current_user, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/person.svg") %>
              <span>Profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/chat-left.svg") %>
              <span>Tweets</span>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(current_user), class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/gear.svg") %>
              <span>Edit</span>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: "delete", class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/box-arrow-right.svg") %>
              <span>Sign out</span>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to users_path, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/people.svg") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/chat-left.svg") %>
              <span>Tweets</span>
            <% end %>
          </li>
          <li>
            <%= link_to login_path, class: 'nav-link' do %>
              <%# <%= inline_svg_tag("bootstrap-icons/box-arrow-in-right.svg") %> 
              <span>Sign in</span>
            <% end %>
          </li>
        <% end %>
      </ul>
      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/layouts/_header1.html.erb
<% if logged_in? %>
    <li class="nav-item">
            <%= link_to users_path, class: 'nav-link', aria: { current: 'page' } do %>
              <%= inline_svg_tag("bootstrap-icons/people.svg") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to current_user, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/person.svg") %>
              <span>Profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/chat-left.svg") %>
              <span>Tweets</span>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(current_user), class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/gear.svg") %>
              <span>Edit</span>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: "delete", class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/box-arrow-right.svg") %>
              <span>Sign out</span>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to users_path, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/people.svg") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path, class: 'nav-link' do %>
              <%= inline_svg_tag("bootstrap-icons/chat-left.svg") %>
              <span>Tweets</span>
            <% end %>
          </li>
          <li>
            <%= link_to login_path, class: 'nav-link' do %>
              <%# <%= inline_svg_tag("bootstrap-icons/box-arrow-in-right.svg") %> 
              <span>Sign in</span>
            <% end %>
          </li>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title> <!-- > full_title was defined in the application helper<!-->
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%# <%= debug(params) if Rails.env.development? %>    <%#  ------------ debugging             %>
    </main>
  </body>
</html>